name: build-test
description: Build & run unit and Cypress tests

runs:
  using: composite
  steps:
    - name: Build packages
      run: pnpm -r build
      shell: bash

    - name: Run type check and unit tests
      run: |
        pnpm --filter svelte-tree-view svelte-check
        pnpm --filter svelte-tree-view test:unit
      shell: bash

    - name: Run tests with Cypress
      id: cypress
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        cache-key: ${{ runner.os }}-node-${{ matrix.node-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        command: pnpm --filter svelte-tree-view cy run
        config: pageLoadTimeout=100000,baseUrl=http://localhost:5185
        install: false
        quiet: true
        start: pnpm --filter site dev
        wait-on: http://[::1]:5185/ # https://github.com/cypress-io/github-action/issues/634
        working-directory: ./packages/svelte-tree-view

      # uses: cypress-io/github-action@v2
      # with:
      #   install: false # Don't install Cypress again
      #   cache-key: ${{ runner.os }}-node-${{ matrix.node-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      #   command: pnpm --filter svelte-tree-view cy run
      #   start: pnpm --filter site dev
      #   wait-on: 'http://localhost:5185'
      #   project: ./packages/svelte-tree-view
      #   browser: chrome
      #   quiet: true

    - name: Export screenshots (on failure only)
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: ./packages/svelte-tree-view/cypress/screenshots
        retention-days: 7

    - name: Export screen recordings (on failure only)
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: ./packages/svelte-tree-view/cypress/videos
        retention-days: 7
