name: pnpm
description: Setup pnpm and install dependencies
inputs:
  cache: # id of input
    description: Path of the pnpm cache
    required: true
    default: .pnpm-store

runs:
  using: composite
  steps:
    - name: Setup caching
      uses: actions/cache@v2
      with:
        path: ${{ env.PNPM_CACHE_FOLDER }}
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-node-${{ matrix.node-version }}-pnpm-

    - name: Install pnpm
      run: npm i pnpm@7 -g
      shell: bash

    - name: Setup pnpm config
      run: pnpm config set store-dir ${{ inputs.cache }}
      shell: bash

    - name: Install dependencies
      run: pnpm i --frozen-lockfile
      shell: bash
